name: Build e Deploy em Runner Local

on:
  push:
    branches:
      - main

jobs:
  build-e-deploy-local:
    runs-on: hello_world

    steps:
      - name: 1. Baixando o código do projeto
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Instalar dependências
        run: npm install

      - name: 4. Reiniciar a aplicação com PM2
        run: |
          npm install pm2 -g
          pm2 start n.js --name "hello_app" || pm2 reload "hello_app"
          echo "Aplicação reiniciada com sucesso via PM2!"