# Nome do seu workflow, pode ser qualquer coisa
name: Build em Runner Local

# Gatilho: Este workflow vai rodar sempre que houver um 'push' na branch 'main'
on:
  push:
    branches:
      - main  # Mude para o nome da sua branch principal se for diferente (ex: master)

# Tarefas a serem executadas
jobs:
  build-na-maquina-local:
    # Ponto CRUCIAL: Diz ao GitHub para rodar este job em um runner
    # que tenha a etiqueta 'hello_world' que você criou.
    runs-on: hello_world

    steps:
      - name: 1. Baixando o código do projeto
        uses: actions/checkout@v4

      - name: 2. Instalando dependências e buildando
        run: |
          npm cache clean --force
          npm i
          npm run dev &  